package com.san.my.dataobj;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AccountDO generated by MyEclipse Persistence Tools
 */

public class AccountDO implements java.io.Serializable {

	// Fields

	private Long accountId;

	private String loginName;

	private String password;

	private String name;

	private String mobile;

	private String address;

	private String village;

	private Date regdate;

	private Set transactions = new HashSet(0);

	private Set slips = new HashSet(0);
    
    private AccountTypesDO accountType;

	// Constructors

	/** default constructor */
	public AccountDO() {
	}

	/** minimal constructor */
	public AccountDO(Long accountId, String loginName) {
		this.accountId = accountId;
		this.loginName = loginName;
	}

	/** full constructor */
	public AccountDO(Long accountId, String loginName, String password,
			String name, String mobile, String address, String village,
			Date regdate, Set transactions, Set slips) {
		this.accountId = accountId;
		this.loginName = loginName;
		this.password = password;
		this.name = name;
		this.mobile = mobile;
		this.address = address;
		this.village = village;
		this.regdate = regdate;
		this.transactions = transactions;
		this.slips = slips;
	}

	// Property accessors


	public String getLoginName() {
		return this.loginName;
	}

	public void setLoginName(String loginName) {
		this.loginName = loginName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}


	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getVillage() {
		return this.village;
	}

	public void setVillage(String village) {
		this.village = village;
	}

	public Date getRegdate() {
		return this.regdate;
	}

	public void setRegdate(Date regdate) {
		this.regdate = regdate;
	}

	public Set getTransactions() {
		return this.transactions;
	}

	public void setTransactions(Set transactions) {
		this.transactions = transactions;
	}

	public Set getSlips() {
		return this.slips;
	}

	public void setSlips(Set slips) {
		this.slips = slips;
	}

    public AccountTypesDO getAccountType()
    {
        return accountType;
    }

    public void setAccountType(AccountTypesDO accountType)
    {
        this.accountType = accountType;
    }

    public String getMobile()
    {
        return mobile;
    }

    public void setMobile(String mobile)
    {
        this.mobile = mobile;
    }

    public Long getAccountId()
    {
        return accountId;
    }

    public void setAccountId(Long accountId)
    {
        this.accountId = accountId;
    }

}