
package com.san.my.dataobj;

import java.util.HashSet;
import java.util.Set;

/**
 * AccountTypesDO generated by MyEclipse Persistence Tools
 */

public class AccountTypesDO implements java.io.Serializable
{

    // Fields

    private Long accountTypeId;
    private String accountType;
    private String description;
    private Set accountses = new HashSet(0);

    // Constructors

    /** default constructor */
    public AccountTypesDO()
    {
    }

    /** minimal constructor */
    public AccountTypesDO(Long accountTypeId)
    {
        this.accountTypeId = accountTypeId;
    }

    /** full constructor */
    public AccountTypesDO(Long accountTypeId, String accountType, String description, Set accountses)
    {
        this.accountTypeId = accountTypeId;
        this.accountType = accountType;
        this.description = description;
        this.accountses = accountses;
    }

    // Property accessors

    public String getAccountType()
    {
        return this.accountType;
    }

    public void setAccountType(String accountType)
    {
        this.accountType = accountType;
    }

    public String getDescription()
    {
        return this.description;
    }

    public void setDescription(String description)
    {
        this.description = description;
    }

    public Set getAccountses()
    {
        return this.accountses;
    }

    public void setAccountses(Set accountses)
    {
        this.accountses = accountses;
    }

    public Long getAccountTypeId()
    {
        return accountTypeId;
    }

    public void setAccountTypeId(Long accountTypeId)
    {
        this.accountTypeId = accountTypeId;
    }

}
