package com.san.my.dataobj;

import java.util.Date;

/**
 * BussinessTransactionDO generated by MyEclipse Persistence Tools
 */

public class BussinessTransactionDO implements java.io.Serializable {

	// Fields

	private Long transId;

	private AccountDO account;

	private SlipDO slip;

	private Date datetime;

	private Double amount;

	private String transFlow;

	private Integer transType;
    
    private String transMode;
    
    private PaymentDetailsDO paymentDetails;

	private String description;

	// Constructors

	/** default constructor */
	public BussinessTransactionDO() {
	}

	/** minimal constructor */
	public BussinessTransactionDO(Long transId, AccountDO account, Date datetime,
			Double amount, String transFlow, Integer transType) {
		this.transId = transId;
		this.account = account;
		this.datetime = datetime;
		this.amount = amount;
		this.transFlow = transFlow;
		this.transType = transType;
	}

	/** full constructor */
	public BussinessTransactionDO(Long transId, AccountDO account, SlipDO slip,
			Date datetime, Double amount, String transFlow, Integer transType,
			String description) {
		this.transId = transId;
		this.account = account;
		this.slip = slip;
		this.datetime = datetime;
		this.amount = amount;
		this.transFlow = transFlow;
		this.transType = transType;
		this.description = description;
	}

	// Property accessors

	public SlipDO getSlip() {
		return this.slip;
	}

	public void setSlip(SlipDO slip) {
		this.slip = slip;
	}

	public Date getDatetime() {
		return this.datetime;
	}

	public void setDatetime(Date datetime) {
		this.datetime = datetime;
	}

	public Double getAmount() {
		return this.amount;
	}

	public void setAmount(Double amount) {
		this.amount = amount;
	}

	public String getTransFlow() {
		return this.transFlow;
	}

	public void setTransFlow(String transFlow) {
		this.transFlow = transFlow;
	}

	public Integer getTransType() {
		return this.transType;
	}

	public void setTransType(Integer transType) {
		this.transType = transType;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

    public String getTransMode()
    {
        return transMode;
    }

    public void setTransMode(String transMode)
    {
        this.transMode = transMode;
    }

    public PaymentDetailsDO getPaymentDetails()
    {
        return paymentDetails;
    }

    public void setPaymentDetails(PaymentDetailsDO paymentDetails)
    {
        this.paymentDetails = paymentDetails;
    }

    public AccountDO getAccount()
    {
        return account;
    }

    public void setAccount(AccountDO account)
    {
        this.account = account;
    }

    public Long getTransId()
    {
        return transId;
    }

    public void setTransId(Long transId)
    {
        this.transId = transId;
    }

}