
package com.san.my.dataobj;

import java.util.Date;

/**
 * PaymentDetails generated by MyEclipse Persistence Tools
 */

public class PaymentDetailsDO implements java.io.Serializable
{

    // Fields

    private Long paymentDetailsId;
    private BussinessTransactionDO bussinessTransactionDO;
    private Date datetime;
    private String paymentMode;
    private String details;

    // Constructors

    /** default constructor */
    public PaymentDetailsDO()
    {
    }

    /** full constructor */
    public PaymentDetailsDO(
        Long paymentDetailsId,
        BussinessTransactionDO transaction,
        Date datetime,
        String paymentMode,
        String details)
    {
        this.paymentDetailsId = paymentDetailsId;
        this.bussinessTransactionDO = transaction;
        this.datetime = datetime;
        this.paymentMode = paymentMode;
        this.details = details;
    }

    // Property accessors


    public Date getDatetime()
    {
        return this.datetime;
    }

    public void setDatetime(Date datetime)
    {
        this.datetime = datetime;
    }

    public String getPaymentMode()
    {
        return this.paymentMode;
    }

    public void setPaymentMode(String paymentMode)
    {
        this.paymentMode = paymentMode;
    }

    public String getDetails()
    {
        return this.details;
    }

    public void setDetails(String details)
    {
        this.details = details;
    }

    public BussinessTransactionDO getBussinessTransactionDO()
    {
        return bussinessTransactionDO;
    }

    public void setBussinessTransactionDO(BussinessTransactionDO bussinessTransactionDO)
    {
        this.bussinessTransactionDO = bussinessTransactionDO;
    }

    public Long getPaymentDetailsId()
    {
        return paymentDetailsId;
    }

    public void setPaymentDetailsId(Long paymentDetailsId)
    {
        this.paymentDetailsId = paymentDetailsId;
    }

}
