package com.san.my.dataobj;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SlipDO generated by MyEclipse Persistence Tools
 */

public class SlipDO implements java.io.Serializable {
    
    private static final long serialVersionUID = 1L;

    // Fields

	private Long slipId;

	private AccountDO buyer;
    
    private AccountDO supplier;

	private SeedDO seed;

	private Date datetime;

	private Long bags;

	private Long looseBag;

	private Long barthi;

	private Double rate;

	private Double qtls;

	private Double hamaliRate;

	private Double adthiRate;

	private Double ccRate;
    
    private String status;

	private String description;

	private Set<BussinessTransactionDO> transactions = new HashSet<BussinessTransactionDO>(0);

	// Constructors

	/** default constructor */
	public SlipDO() {
	}

	/** minimal constructor */
	public SlipDO(Long slipId) {
		this.slipId = slipId;
	}

	/** full constructor */
	public SlipDO(Long slipId, AccountDO buyer, AccountDO supplier, SeedDO seed, Date datetime,
			String farmarName, String farmarVillage, Long bags,
			Long looseBag, Long barthi, Double rate, Double qtls,
			Double hamaliRate, Double adthiRate, Double ccRate, String status,
			String description, Set<BussinessTransactionDO> transactions) {
		this.slipId = slipId;
		this.buyer = buyer;
        this.supplier = supplier;
		this.seed = seed;
		this.datetime = datetime;
		this.bags = bags;
		this.looseBag = looseBag;
		this.barthi = barthi;
		this.rate = rate;
		this.qtls = qtls;
		this.hamaliRate = hamaliRate;
		this.adthiRate = adthiRate;
		this.ccRate = ccRate;
        this.status = status;
		this.description = description;
		this.transactions = transactions;
	}

	// Property accessors



	public Date getDatetime() {
		return this.datetime;
	}

	public void setDatetime(Date datetime) {
		this.datetime = datetime;
	}

	public Double getRate() {
		return this.rate;
	}

	public void setRate(Double rate) {
		this.rate = rate;
	}

	public Double getQtls() {
		return this.qtls;
	}

	public void setQtls(Double qtls) {
		this.qtls = qtls;
	}

	public Double getHamaliRate() {
		return this.hamaliRate;
	}

	public void setHamaliRate(Double hamaliRate) {
		this.hamaliRate = hamaliRate;
	}

	public Double getAdthiRate() {
		return this.adthiRate;
	}

	public void setAdthiRate(Double adthiRate) {
		this.adthiRate = adthiRate;
	}

	public Double getCcRate() {
		return this.ccRate;
	}

	public void setCcRate(Double ccRate) {
		this.ccRate = ccRate;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<BussinessTransactionDO> getTransactions() {
		return this.transactions;
	}

	public void setTransactions(Set<BussinessTransactionDO> transactions) {
		this.transactions = transactions;
	}

	public Long getBags() {
		return bags;
	}

	public void setBags(Long bags) {
		this.bags = bags;
	}

	public Long getBarthi() {
		return barthi;
	}

	public void setBarthi(Long barthi) {
		this.barthi = barthi;
	}

	public Long getLooseBag() {
		return looseBag;
	}

	public void setLooseBag(Long looseBag) {
		this.looseBag = looseBag;
	}

    public SeedDO getSeed()
    {
        return seed;
    }

    public void setSeed(SeedDO seed)
    {
        this.seed = seed;
    }

    public Long getSlipId()
    {
        return slipId;
    }

    public void setSlipId(Long slipId)
    {
        this.slipId = slipId;
    }

    public AccountDO getBuyer()
    {
        return buyer;
    }

    public void setBuyer(AccountDO buyer)
    {
        this.buyer = buyer;
    }

    public String getStatus()
    {
        return status;
    }

    public void setStatus(String status)
    {
        this.status = status;
    }

    public AccountDO getSupplier()
    {
        return supplier;
    }

    public void setSupplier(AccountDO supplier)
    {
        this.supplier = supplier;
    }

}